name: hmforecast
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pytorch-lightning
  - torchmetrics
  - rasterio
  - shapely
  - pyproj
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - numpy
  - scikit-learn
  - hydra-core
  - omegaconf
  - pip
  - pip:
    - torchgeo
    - einops
    - wandb
    - light-the-torch

