program: scripts/train_lightning.py
method: random  # Random search for quick testing
metric:
  name: val_full/total_loss_avg
  goal: minimize

parameters:
  # Model architecture - sweep between default and 2x default
  hidden_dim:
    values: [64, 128]
  num_layers:
    values: [2, 4]
  kernel_size:
    values: [3, 5]
  locenc_out_channels:
    values: [8, 16]
  locenc_legendre_polys:
    values: [8, 16]
  
  # Fixed parameters from command line
  accumulate_grad_batches:
    value: 4
  train_chips:
    value: 64
  val_chips:
    value: 32
  batch_size:
    value: 8
  train_mode:
    value: random
  val_mode:
    value: random
  stride:
    value: 64
  max_epochs:
    value: 5
  use_location_encoder:
    value: true
  predict_after_training:
    value: false
  histogram_warmup_epochs:
    value: 0
  ssim_weight:
    value: 0.15
  laplacian_weight:
    value: 0.2
  histogram_weight:
    value: 1.15
